# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pkg_netproxy/UavStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class UavStatus(genpy.Message):
  _md5sum = "1e2778f4d8e4263c2ff410b965eb52cc"
  _type = "pkg_netproxy/UavStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
#位姿信息
float32 roll
float32 pitch
float32 yaw

#GPS位置
float64 latitude
float64 longitude
float64 altitude

#气压计高度
float32 baro_altitude
#激光测高
float32 tf_altitude

#三轴速度
float32 velocity_n
float32 velocity_e
float32 velocity_d

#目标点信息
float64 g_latitude
float64 g_longitude
float64 g_altitude

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','roll','pitch','yaw','latitude','longitude','altitude','baro_altitude','tf_altitude','velocity_n','velocity_e','velocity_d','g_latitude','g_longitude','g_altitude']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float64','float64','float64','float32','float32','float32','float32','float32','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,roll,pitch,yaw,latitude,longitude,altitude,baro_altitude,tf_altitude,velocity_n,velocity_e,velocity_d,g_latitude,g_longitude,g_altitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UavStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.baro_altitude is None:
        self.baro_altitude = 0.
      if self.tf_altitude is None:
        self.tf_altitude = 0.
      if self.velocity_n is None:
        self.velocity_n = 0.
      if self.velocity_e is None:
        self.velocity_e = 0.
      if self.velocity_d is None:
        self.velocity_d = 0.
      if self.g_latitude is None:
        self.g_latitude = 0.
      if self.g_longitude is None:
        self.g_longitude = 0.
      if self.g_altitude is None:
        self.g_altitude = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.
      self.baro_altitude = 0.
      self.tf_altitude = 0.
      self.velocity_n = 0.
      self.velocity_e = 0.
      self.velocity_d = 0.
      self.g_latitude = 0.
      self.g_longitude = 0.
      self.g_altitude = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3f3d5f3d().pack(_x.roll, _x.pitch, _x.yaw, _x.latitude, _x.longitude, _x.altitude, _x.baro_altitude, _x.tf_altitude, _x.velocity_n, _x.velocity_e, _x.velocity_d, _x.g_latitude, _x.g_longitude, _x.g_altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.roll, _x.pitch, _x.yaw, _x.latitude, _x.longitude, _x.altitude, _x.baro_altitude, _x.tf_altitude, _x.velocity_n, _x.velocity_e, _x.velocity_d, _x.g_latitude, _x.g_longitude, _x.g_altitude,) = _get_struct_3f3d5f3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3f3d5f3d().pack(_x.roll, _x.pitch, _x.yaw, _x.latitude, _x.longitude, _x.altitude, _x.baro_altitude, _x.tf_altitude, _x.velocity_n, _x.velocity_e, _x.velocity_d, _x.g_latitude, _x.g_longitude, _x.g_altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.roll, _x.pitch, _x.yaw, _x.latitude, _x.longitude, _x.altitude, _x.baro_altitude, _x.tf_altitude, _x.velocity_n, _x.velocity_e, _x.velocity_d, _x.g_latitude, _x.g_longitude, _x.g_altitude,) = _get_struct_3f3d5f3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f3d5f3d = None
def _get_struct_3f3d5f3d():
    global _struct_3f3d5f3d
    if _struct_3f3d5f3d is None:
        _struct_3f3d5f3d = struct.Struct("<3f3d5f3d")
    return _struct_3f3d5f3d
