(cl:in-package pkg_netproxy-msg)
(cl:export '(HEADER-VAL
          HEADER
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          BARO_ALTITUDE-VAL
          BARO_ALTITUDE
          TF_ALTITUDE-VAL
          TF_ALTITUDE
          VELOCITY_N-VAL
          VELOCITY_N
          VELOCITY_E-VAL
          VELOCITY_E
          VELOCITY_D-VAL
          VELOCITY_D
          G_LATITUDE-VAL
          G_LATITUDE
          G_LONGITUDE-VAL
          G_LONGITUDE
          G_ALTITUDE-VAL
          G_ALTITUDE
))